name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # No need for username/password - trusted publishing handles authentication!
        verbose: true