name: Create Release

on:
  push:
    branches: [ main ]
    paths: [ 'pyproject.toml' ]  # Only trigger when version changes

permissions:
  contents: write  # Required to create releases
  pull-requests: read

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip-release')"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Extract version
      id: version
      run: |
        VERSION=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
    
    - name: Check if release exists
      id: check_release
      run: |
        if gh release view v${{ steps.version.outputs.version }} >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Release
      if: steps.check_release.outputs.exists == 'false'
      run: |
        gh release create v${{ steps.version.outputs.version }} \
          --title "Release v${{ steps.version.outputs.version }}" \
          --notes "Automated release for version ${{ steps.version.outputs.version }}" \
          --latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}